/*
	Student ID: 1155046993
	Name: YE ZHIZHEN
*/
/* Query 1 */
Spool result1.lst
SELECT T.TID, T.TITLE, T.TDATE, T.PERMISSION
FROM TOPIC T, FORUM F, CATEGORY C
WHERE T.FID = F.FID AND F.CID = C.CID AND C.CTITLE = 'Digital'
ORDER BY TID DESC;
Spool off

/* Query 2 */
Spool result2.lst
SELECT F.FID, F.FTITLE, COUNT(T.TID) AS NUM_OF_TOPIC
FROM FORUM F, TOPIC T
WHERE F.FID = T.FID
GROUP BY F.FID, F.FTITLE
ORDER BY FTITLE ASC;
Spool off

/* Query 3 */
Spool result3.lst
SELECT T.TID, T.TITLE
FROM TOPIC T
WHERE NOT EXISTS(
SELECT *
FROM POST P
WHERE P.TID = T.TID)
ORDER BY T.TID DESC;
Spool off

/* Query 4 */
Spool result4.lst
SELECT  U.USERID, U.NAME
FROM FUSER U
WHERE NOT EXISTS
(SELECT *
FROM POST P, TOPIC T
WHERE P.USERID = U.USERID AND T.USERID = U.USERID AND P.TID = T.TID)
ORDER BY U.NAME ASC;
Spool off

/* Query 5 */
Spool result5.lst
SELECT U.USERID, U.NAME
FROM FUSER U
WHERE U.PERMISSION >= (
SELECT MAX(T.PERMISSION)
FROM TOPIC T)
AND U.PERMISSION >= (
SELECT MAX(F.PERMISSION)
FROM FORUM F)
AND U.PERMISSION >= (
SELECT MAX(C.PERMISSION)
FROM CATEGORY C)
ORDER BY U.USERID DESC;
Spool off

/* Query 6 */
Spool result6.lst
SELECT F.FTITLE, AVG(CUM.CP) AS AVG_POPULARITY 
FROM (
SELECT COUNT(*) AS CP, T2.TID AS T2_TID, T2.FID AS T2_FID
FROM TOPIC T2, 
(SELECT DISTINCT TID, USERID 
FROM POST 
)P2
WHERE T2.TID = P2.TID
GROUP BY T2.TID, T2.FID
) CUM,  FORUM F
WHERE F.FID = CUM.T2_FID 
GROUP BY F.FID, F.FTITLE
ORDER BY AVG_POPULARITY DESC; 
Spool off

/* Query 7 */
Spool result7.lst
SELECT T_TID AS TID, T_TITLE AS TITLE, T_DATE AS TDATE
FROM(
SELECT T.TID as T_TID, T.TITLE AS T_TITLE, T.TDATE AS T_DATE, ROWNUM AS RN 
FROM (
     SELECT *
     FROM TOPIC, FORUM
     WHERE TOPIC.FID = FORUM.FID AND FORUM.FTITLE = 'Camera'       
     ORDER BY TDATE DESC
     ) T 
)
WHERE  RN>=11 AND RN<=20;
Spool off

/* Query 8 */
Spool result8.lst
SELECT T.TID, T.TITLE, M_PDATE AS LATEST_UPDATE_DATE,  RESULT1.NUM_OF_REPLY
FROM TOPIC T, 
       (SELECT MAX(NT.REPLY_NUM) AS NUM_OF_REPLY, NT.TID, M_PDATE
       FROM 
       (SELECT COUNT(*) AS REPLY_NUM, TID, MAX(PDATE) AS M_PDATE
       FROM POST
       GROUP BY TID
       ) NT
	GROUP BY NT.TID, M_PDATE
       )RESULT1
WHERE T.TID = RESULT1.TID
GROUP BY T.TID, T.TITLE, T.TDATE, RESULT1.NUM_OF_REPLY, M_PDATE
ORDER BY M_PDATE DESC;
Spool off


